### ISSUE TITLE
Full with parameter as well as X and Y

### ISSUE THREAD

**Issue by dkrutsko** [sylvainbaronnet/postcss-position-alt#2]
Hey there, huge fan of this plugin. I was working on a design the other day and found a need to set ltrb to a single number. Any thoughts on supporting `absolute: full 0.5rem` syntax to generate `left/top/right/bottom: 0.5rem;`.

Moreover, maybe also supporting `x` and `y` to control the `left/right` and `top/bottom` properties like `absolute: x 0.5rem y 1rem`? If `x` and `y` are too short, maybe `horizontal` and `vertical` instead.

**Comment by sylvainbaronnet** [comment]
Hi @dkrutsko ,

I'm very sorry I completely missed your issue, these are great ideas. Do you want to create a PR ? Maybe @Grawl ? Otherwise I'll try to work on it soon

**Comment by Grawl** [comment]
not sure I can

**Comment by sylvainbaronnet** [comment]
Hi,

I just published a new version with @dkrutsko suggestions and @Grawl contribution : 

https://github.com/sylvainbaronnet/postcss-position-alt/blob/master/CHANGELOG.md#version-070

**Comment by dkrutsko** [comment]
Super nice, thanks a lot!
